title: Shahul Hameed
description: >-
  A programming freak.

baseurl: "/hameid"
url: ""

twitter_username: shahthepro
github_username:  shahthepro

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed